Add qiskit passes
QuTech-Delft/qtt pull request #784
Opened 2021-08-05 12:26 UTC by eendebakpt

Adds qiskit passes for:

- Removal of small gates
- Removal of diagonal gates
- Decomposition of `U` and `CX` gates

2021-09-28 12:31 UTC, QFer requested changes

2021-09-28 12:31 UTC, QFer commented on src/tests/unittests/qiskit/test_passes.py
> +        qcd = delay_pass(qc)
This pass is not tested only executed. qcd is overwritten in line 136 without testing it.

2021-09-28 12:31 UTC, QFer commented on src/tests/unittests/qiskit/test_passes.py
> +class TestQiskitPasses(unittest.TestCase):
The tests are not testing edge cases of all passes. From code review I cannot tell if the passes are error free in edge cases.

2021-10-04 10:51 UTC, eendebakpt commented on src/qtt/qiskit/passes.py
> +        self._empty_dag1 = qiskit.converters.circuit_to_dag(QuantumCircuit(1))
For efficiency we do not want to re-create a dag every time

2021-10-04 10:52 UTC, eendebakpt commented on src/qtt/qiskit/passes.py
> +            return np.mod(x + np.pi, 2 * np.pi) - np.pi
It does not matter here, we only care whether the resulting angle is close to zero. Changing the method to leave pi the same would involve another if statement

2021-10-04 10:56 UTC, eendebakpt commented on src/qtt/qiskit/passes.py
> +    """Remove diagonal gates (including diagonal 2Q gates) at the start of a circuit.
No, Tofolli is not diagonal in the measurement basis.

2021-12-06 08:15 UTC, QFer requested changes

2021-12-06 08:15 UTC, QFer commented on src/tests/unittests/qiskit/test_passes.py
> +import unittest
Please add `__init__.py` to this qiskit directory in unittests

2021-12-06 14:17 UTC, QFer approved these changes

2021-12-06 22:14 UTC, merged