Some small fixes to the optimization tools
QuTech-Delft/qtt pull request #840
Opened 2022-03-24 12:57 UTC by eendebakpt

* Type annotations
* Fix typos
* Add option to use general minimalization methods (and not just residuals such as least squares)

2022-04-07 15:13 UTC, QFer requested changes
There are some other quick improvements (not touch by your changes) but that can be done:
1. number_of_evaluations can also be a property (and used in line 189 instead of method call
2. line 162: self._number_of_evaluations += 1

2022-04-07 15:13 UTC, QFer commented on src/qtt/utilities/optimization.py
> +            The list of parameters
There are a few other misspelled words: line 159 resisual, line 111: Apppend

2022-04-07 18:30 UTC, peendebak commented on src/qtt/utilities/optimization.py
> +            ax.set_ylabel('Residual')
Both labels make sense for scipy. The original implementation was not good, so while it appears that residual_fitting=False was the original default, it fact we used it in residual mode (just not for plotting)

2022-04-08 07:03 UTC, QFer approved these changes

2022-04-08 08:12 UTC, merged